name: Build Feature Branch

on:
  # Triggers only for the feature/ branches
  push:
    branches: [ 'feature/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag flask-sample:$(date +'%Y-%m-%d')
