name: Build Feature Branch

on:
  # Triggers only for the feature/ branches
  push:
    branches: [ 'feature/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Print the Secret
        run: echo ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/flask-sample:$(date +'%Y-%m-%d')

      - name: Generate Provenance
        uses: slsa-framework/github-action-demo@v0.1
        with:
          command: generate
          subcommand: container
          arguments: --repository ${{ secrets.ACR_LOGIN_SERVER }}/flask-sample --tag-name $(date +'%Y-%m-%d') --output-path 'provenance.json'

      - name: Login to the Container Registry  
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_SECRET }}
      
      - name: Push Image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/flask-sample:$(date +'%Y-%m-%d')
