name: sign-local-image

on:
  workflow_dispatch

env:
  NOTATION_EXPERIMENTAL: 1

jobs:
  sign-local-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Display environment
        run: |
          echo "NOTATION_EXPERIMENTAL: $NOTATION_EXPERIMENTAL"
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install tree tool
        run: |
          sudo apt-get update
          sudo apt-get install tree
      - name: Setup Notation CLI
        uses: notaryproject/notation-action/setup@v1
        with:
          version: "1.0.0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build OCI image and sign
        run: |
          utils/sign-oci-layout.sh